"""Learn optimal fusion weights from synthetic LTR labels.

Reads data/ltr_labels.csv (generated by generate_labels.py), computes
signal scores for ALL 3 channels for each (context, fragrance) pair,
then trains a logistic regression to learn all weights simultaneously.

Signal 2 (image) uses a proxy: context-derived CLIP head probabilities
rather than a real outfit photo — the oracle head probs represent what
CLIP *would* output for a perfectly-matching outfit, giving us a valid
third feature without needing actual images.

Outputs:
  - data/learned_weights.json  — fusion weights to apply to fusion.py
"""
from __future__ import annotations

import json
import logging
import os
import sys

import numpy as np
import pandas as pd
from dotenv import load_dotenv

load_dotenv()
sys.path.insert(0, "src")
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

LABELS_PATH = "data/ltr_labels.csv"
OUTPUT_PATH = "data/learned_weights.json"
CORPUS_PATH = os.environ.get("CORPUS_METADATA_PATH", "data/vibescent_enriched.csv")
MINILM_CORPUS = "artifacts/minilm_corpus/embeddings.npy"

# ── Load labels ───────────────────────────────────────────────────────────────
if not os.path.exists(LABELS_PATH):
    raise FileNotFoundError(f"{LABELS_PATH} not found. Run generate_labels.py first.")

labels_df = pd.read_csv(LABELS_PATH)
log.info("Loaded %d labelled pairs", len(labels_df))

labels_df["relevant"] = (labels_df["relevance_score"] >= 0.6).astype(int)
log.info("Positive pairs: %d / %d", labels_df["relevant"].sum(), len(labels_df))

# ── Load corpus ───────────────────────────────────────────────────────────────
corpus_df = pd.read_csv(CORPUS_PATH, low_memory=False)

has_text_signal = False
if os.path.exists(MINILM_CORPUS):
    log.info("Loading MiniLM corpus embeddings from %s", MINILM_CORPUS)
    corpus_emb = np.load(MINILM_CORPUS)
    frag_id_to_idx: dict[str, int] = {
        str(row.get("fragrance_id", i)): i for i, row in corpus_df.iterrows()
    }
    log.info("Loading MiniLM query embedder...")
    from vibescents.embeddings import SentenceTransformerEmbedder
    embedder = SentenceTransformerEmbedder("sentence-transformers/all-MiniLM-L6-v2")
    has_text_signal = True
else:
    log.warning("MiniLM corpus not found — text signal will default to 0.5")

# Build frag_id → corpus row lookup
frag_id_to_row: dict[str, dict] = {
    str(row.get("fragrance_id", i)): row for i, row in corpus_df.iterrows()
}

# ── Helper ────────────────────────────────────────────────────────────────────
from vibescents.query import context_to_query_string
from vibescents.schemas import ContextInput
from vibescents.image_scoring import ImageHeadProbabilities, image_score_likelihood


def _safe_float(val, default: float = 0.5) -> float:
    if val is None:
        return default
    try:
        v = float(val)
        return default if (v != v) else v  # NaN check without numpy
    except (TypeError, ValueError):
        return default


# ── Signal 1: Text (MiniLM cosine similarity) ─────────────────────────────────
def compute_text_score(context_row: pd.Series, frag_id: str) -> float:
    """Cosine similarity between a MiniLM query vector and the corpus embedding."""
    if not has_text_signal:
        return 0.5
    ctx = ContextInput(
        eventType=context_row.get("event_type"),
        timeOfDay=context_row.get("time_of_day"),
        mood=context_row.get("mood"),
    )
    q_vec = embedder.embed_multimodal_query(text=context_to_query_string(ctx))[0]
    idx = frag_id_to_idx.get(str(frag_id))
    if idx is None:
        return 0.5
    c_vec = corpus_emb[idx].astype(np.float32)
    c_vec /= np.linalg.norm(c_vec) + 1e-8
    return float(np.dot(q_vec, c_vec))


# ── Signal 2: Image (oracle proxy CLIP head probabilities) ────────────────────
def _build_oracle_head_probs(context_row: pd.Series) -> ImageHeadProbabilities:
    """Derive what CLIP *would* output for an ideal outfit matching this context.

    - Heads we know from context (formality, time-of-day, frequency) get a
      near-one-hot distribution (eps smoothing to avoid log(0) in NLL).
    - Heads we cannot know without a real image (season, gender) get a
      uniform distribution, contributing zero discriminative signal.
    """
    eps = 0.05

    event = str(context_row.get("event_type", "")).lower()

    # Formality [casual=0, smart-casual=1, formal=2]
    if event in ("gala", "wedding", "business"):
        formal = np.array([eps, eps, 1.0 - 2 * eps], dtype=np.float32)
    elif event in ("casual", "festival"):
        formal = np.array([1.0 - 2 * eps, eps, eps], dtype=np.float32)
    else:
        formal = np.array([eps, 1.0 - 2 * eps, eps], dtype=np.float32)

    # Season [spring=0, summer=1, fall=2, winter=3] — unknown without image
    season = np.full(4, 0.25, dtype=np.float32)

    # Time-of-day [day=0, night=1]
    tod = str(context_row.get("time_of_day", "")).lower()
    if tod in ("evening", "night"):
        time = np.array([eps, 1.0 - eps], dtype=np.float32)
    elif tod in ("morning", "afternoon"):
        time = np.array([1.0 - eps, eps], dtype=np.float32)
    else:
        time = np.array([0.5, 0.5], dtype=np.float32)

    # Gender [male=0, female=1, neutral=2] — unknown without image
    gender = np.array([1 / 3, 1 / 3, 1 / 3], dtype=np.float32)

    # Frequency [occasional=0, everyday=1]
    if event in ("gala", "wedding"):
        frequency = np.array([1.0 - eps, eps], dtype=np.float32)
    elif event in ("casual", "festival"):
        frequency = np.array([eps, 1.0 - eps], dtype=np.float32)
    else:
        frequency = np.array([0.5, 0.5], dtype=np.float32)

    return ImageHeadProbabilities(
        formal=formal,
        season=season,
        time=time,
        gender=gender,
        frequency=frequency,
    )


def compute_image_proxy_score(context_row: pd.Series, frag_row: dict) -> float:
    """Proxy CLIP score: runs the live engine scoring function against oracle head probs.

    The score measures how well the fragrance's metadata (formality, day_night,
    likely_season, gender) aligns with the inferred visual context from the event
    and time-of-day labels.
    """
    head_probs = _build_oracle_head_probs(context_row)
    frag = {
        "formality":     _safe_float(frag_row.get("formality"), 0.5),
        "day_night":     _safe_float(frag_row.get("day_night"), 0.5),
        "likely_season": str(frag_row.get("likely_season") or "all-season"),
        "gender":        str(frag_row.get("gender") or "neutral"),
        "frequency":     str(frag_row.get("frequency") or "everyday"),
    }
    try:
        return image_score_likelihood(head_probs.as_dict(), frag)
    except Exception:
        return 0.5


# ── Signal 3: Structured (metadata arithmetic match) ─────────────────────────
def compute_structured_score(context_row: pd.Series, frag_row: dict) -> float:
    """Three-part arithmetic check: formality, freshness, and time-of-day."""
    scores = []

    event = str(context_row.get("event_type", "")).lower()
    formality = _safe_float(frag_row.get("formality"), 0.5)
    if event in ("gala", "wedding", "business"):
        scores.append(formality)
    elif event in ("casual", "festival"):
        scores.append(1.0 - formality)
    else:
        scores.append(0.5)

    mood = str(context_row.get("mood", "")).lower()
    fresh_warm = _safe_float(frag_row.get("fresh_warm"), 0.5)
    if mood == "fresh":
        scores.append(1.0 - fresh_warm)
    elif mood == "warm":
        scores.append(fresh_warm)
    else:
        scores.append(0.5)

    tod = str(context_row.get("time_of_day", "")).lower()
    day_night = _safe_float(frag_row.get("day_night"), 0.5)
    if tod in ("evening", "night"):
        scores.append(day_night)
    elif tod in ("morning", "afternoon"):
        scores.append(1.0 - day_night)
    else:
        scores.append(0.5)

    return float(np.mean(scores))


# ── Score all pairs ───────────────────────────────────────────────────────────
log.info("Computing signal scores for %d pairs...", len(labels_df))
text_scores, image_scores, structured_scores = [], [], []

for i, row in labels_df.iterrows():
    frag_id = str(row["fragrance_id"])
    frag_row = frag_id_to_row.get(frag_id, {})
    text_scores.append(compute_text_score(row, frag_id))
    image_scores.append(compute_image_proxy_score(row, frag_row))
    structured_scores.append(compute_structured_score(row, frag_row))
    if (i + 1) % 50 == 0:
        log.info("  %d / %d done", i + 1, len(labels_df))

labels_df["signal_text"] = text_scores
labels_df["signal_image"] = image_scores
labels_df["signal_structured"] = structured_scores

log.info(
    "Signal means — text: %.3f  image: %.3f  structured: %.3f",
    np.mean(text_scores), np.mean(image_scores), np.mean(structured_scores),
)

# ── Train logistic regression on all 3 features ───────────────────────────────
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import MinMaxScaler

X = labels_df[["signal_text", "signal_image", "signal_structured"]].values
y = labels_df["relevant"].values

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

model = LogisticRegression(fit_intercept=False, C=1.0, max_iter=500)
model.fit(X_scaled, y)

cv = cross_val_score(model, X_scaled, y, cv=5, scoring="roc_auc")
log.info("Cross-val AUC: %.3f ± %.3f", cv.mean(), cv.std())

raw = model.coef_[0]
log.info(
    "Raw logistic coefficients — text: %.4f  image: %.4f  structured: %.4f",
    raw[0], raw[1], raw[2],
)

# Floor negative coefficients at a small epsilon (a negative weight means the
# signal actively hurts ranking; we keep it at minimal influence rather than
# inverting the channel entirely).
raw = np.maximum(raw, 0.01)
norm = raw / raw.sum()

learned = {
    "text":       round(float(norm[0]), 4),
    "image":      round(float(norm[1]), 4),
    "structured": round(float(norm[2]), 4),
}
log.info("Learned fusion weights: %s", learned)
log.info("Sum = %.4f", sum(learned.values()))

with open(OUTPUT_PATH, "w") as f:
    json.dump(learned, f, indent=2)

log.info("Saved to %s", OUTPUT_PATH)
log.info("Paste these into DEFAULT_FUSION_WEIGHTS in src/vibescents/fusion.py")
