"""Patch harsh_week5_qwen3vl.ipynb: Stage 3 (TF32/FA2/compile) + Stage 4 (batch reranker)."""
import json

NB_PATH = '/home/bossman/projects/vibescent/notebooks/harsh_week5_qwen3vl.ipynb'
with open(NB_PATH) as f:
    nb = json.load(f)

# ── Cell 4 (Stage 3) ──────────────────────────────────────────────────────────
stage3_new = (
    "# Stage 3: Load Qwen3-VL-Embedding-8B + Qwen3-VL-Reranker-8B\n"
    "# Both in bfloat16. Total VRAM: ~34 GB. No quantisation needed on 80 GB GPU.\n"
    "PIPELINE_VERSION = globals().get('PIPELINE_VERSION', 'w5v1')\n"
    "import time, torch, gc\n"
    "from tqdm.auto import tqdm\n"
    "import sys; sys.path.insert(0, REPO_DIR)\n"
    "_t0 = time.perf_counter()\n"
    "\n"
    "gc.collect(); torch.cuda.empty_cache()\n"
    "\n"
    "# TF32: same dynamic range as float32, 10 fewer mantissa bits, ~30% faster matmuls\n"
    "# Safe on Blackwell/Ampere — enabled by default since PyTorch 1.12 but be explicit\n"
    "torch.backends.cuda.matmul.allow_tf32 = True\n"
    "torch.backends.cudnn.allow_tf32 = True\n"
    "\n"
    "# ── 1. Qwen3-VL-Embedding-8B ─────────────────────────────────────────────────\n"
    "EMBEDDER_MODEL = 'Qwen/Qwen3-VL-Embedding-8B'\n"
    "print(f'Loading {EMBEDDER_MODEL} (bfloat16) ...')\n"
    "from vibescents.embeddings import Qwen3VLMultimodalEmbedder\n"
    "from vibescents.settings import Settings\n"
    "\n"
    "_s = Settings(api_key=None)\n"
    "Qwen3VLMultimodalEmbedder._BATCH_SIZE = 8  # conservative for inference\n"
    "VL_EMBEDDER = Qwen3VLMultimodalEmbedder(settings=_s, load_in_8bit=False)\n"
    "\n"
    "_warmup = VL_EMBEDDER.embed_multimodal_documents(['warmup fragrance'])\n"
    "EMB_DIM = _warmup.shape[1]\n"
    "print(f'Embedder ready. dim={EMB_DIM}  VRAM used: {torch.cuda.memory_allocated()/1e9:.1f} GB')\n"
    "\n"
    "assert EMB_DIM == CORPUS_EMBEDDINGS.shape[1], (\n"
    "    f'Embedding dimension mismatch: model={EMB_DIM} vs corpus={CORPUS_EMBEDDINGS.shape[1]}.\\n'\n"
    "    'Re-run Stage 0 (or harsh_offline_pipeline.ipynb) to regenerate corpus embeddings.'\n"
    ")\n"
    "print(f'Dimension check passed: {EMB_DIM}')\n"
    "\n"
    "# ── 2. Qwen3-VL-Reranker-8B ──────────────────────────────────────────────────\n"
    "RERANKER_MODEL = 'Qwen/Qwen3-VL-Reranker-8B'\n"
    "print(f'\\nLoading {RERANKER_MODEL} (bfloat16, flash_attention_2) ...')\n"
    "\n"
    "from transformers import AutoProcessor, AutoModelForCausalLM\n"
    "\n"
    "VL_RERANKER_PROC = AutoProcessor.from_pretrained(\n"
    "    RERANKER_MODEL, trust_remote_code=True\n"
    ")\n"
    "VL_RERANKER_MODEL = AutoModelForCausalLM.from_pretrained(\n"
    "    RERANKER_MODEL,\n"
    "    torch_dtype=torch.bfloat16,\n"
    "    device_map='cuda',\n"
    "    trust_remote_code=True,\n"
    "    attn_implementation='flash_attention_2',\n"
    ").eval()\n"
    "\n"
    "# torch.compile: fuses ops, reduces kernel-launch overhead\n"
    "# mode='reduce-overhead' is safe with dynamic shapes (padding varies per batch)\n"
    "try:\n"
    "    VL_RERANKER_MODEL = torch.compile(\n"
    "        VL_RERANKER_MODEL, mode='reduce-overhead', fullgraph=False\n"
    "    )\n"
    "    print('torch.compile applied to reranker')\n"
    "except Exception as _ce:\n"
    "    print(f'torch.compile skipped ({_ce}) — running uncompiled')\n"
    "\n"
    "_tok = VL_RERANKER_PROC.tokenizer\n"
    "_YES_IDS = _tok.encode('yes', add_special_tokens=False)\n"
    "_NO_IDS  = _tok.encode('no',  add_special_tokens=False)\n"
    "_YES_ID  = _YES_IDS[0] if _YES_IDS else -1\n"
    "_NO_ID   = _NO_IDS[0]  if _NO_IDS  else -1\n"
    "\n"
    "print(f'Reranker ready. yes_id={_YES_ID} no_id={_NO_ID}')\n"
    "print(f'Total VRAM used: {torch.cuda.memory_allocated()/1e9:.1f} GB / '\n"
    "      f'{torch.cuda.get_device_properties(0).total_memory/1e9:.0f} GB')\n"
    "print(f'\\nStage 3 done in {time.perf_counter()-_t0:.0f}s')\n"
)

# ── Cell 5 (Stage 4) ──────────────────────────────────────────────────────────
stage4_new = (
    "# Stage 4: Build VibeScentEngine — Qwen3-VL unified stack\n"
    "PIPELINE_VERSION = globals().get('PIPELINE_VERSION', 'w5v1')\n"
    "import base64, io, os, tempfile, time\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import torch\n"
    "import torch.nn.functional as F\n"
    "from vibescents.backend_app import RecommendationEngine\n"
    "from vibescents.schemas import RecommendRequest, RecommendResponse, FragranceRecommendation\n"
    "from vibescents.structured_scorer import compute_structured_scores\n"
    "\n"
    "_TOPK  = 8   # retrieve top-8, batch-rerank all 8 in ONE forward pass -> top-3\n"
    "_FINAL = 3\n"
    "_SYS_PROMPT = (\n"
    "    'You are a world-class fragrance consultant. '\n"
    "    'Given an outfit image and occasion context, assess whether a fragrance is a strong match. '\n"
    "    'Consider: formality, mood, season, and scent-aesthetic harmony. '\n"
    "    'Answer only \"yes\" or \"no\".'\n"
    ")\n"
    "\n"
    "\n"
    "def _embed_query(context_str, image_bytes):\n"
    "    if image_bytes:\n"
    "        import tempfile as _tf_mod, os as _os\n"
    "        with _tf_mod.NamedTemporaryFile(suffix='.jpg', delete=False) as _tf:\n"
    "            _tf.write(image_bytes)\n"
    "            _tmp = _tf.name\n"
    "        try:\n"
    "            vec = VL_EMBEDDER.embed_multimodal_query(text=context_str, image_path=_tmp)\n"
    "        finally:\n"
    "            _os.unlink(_tmp)\n"
    "    else:\n"
    "        vec = VL_EMBEDDER.embed_multimodal_documents([context_str])\n"
    "    vec = vec.astype('float32').reshape(1, -1)\n"
    "    vec /= (np.linalg.norm(vec, axis=1, keepdims=True) + 1e-9)\n"
    "    return vec\n"
    "\n"
    "\n"
    "@torch.no_grad()\n"
    "def _rerank_batch(context_str, frag_texts, image_bytes):\n"
    "    \"\"\"Single batched forward pass for all candidates.\n"
    "    Replaces N sequential calls (~25-40s) with one padded batch (~2-3s).\n"
    "    Returns list[float] of P(yes) scores, same length as frag_texts.\n"
    "    \"\"\"\n"
    "    from qwen_vl_utils import process_vision_info\n"
    "    import base64 as _b64\n"
    "\n"
    "    _img_b64 = _b64.b64encode(image_bytes).decode() if image_bytes else None\n"
    "    texts_for_proc, all_messages = [], []\n"
    "\n"
    "    for frag_text in frag_texts:\n"
    "        user_parts = []\n"
    "        if _img_b64:\n"
    "            user_parts.append({\n"
    "                'type': 'image',\n"
    "                'image': f'data:image/jpeg;base64,{_img_b64}',\n"
    "            })\n"
    "        user_parts.append({\n"
    "            'type': 'text',\n"
    "            'text': (\n"
    "                f'Occasion context: {context_str}\\n\\n'\n"
    "                f'Fragrance candidate: {frag_text}\\n\\n'\n"
    "                'Is this fragrance a strong match for the outfit and occasion?'\n"
    "            ),\n"
    "        })\n"
    "        messages = [\n"
    "            {'role': 'system', 'content': _SYS_PROMPT},\n"
    "            {'role': 'user',   'content': user_parts},\n"
    "        ]\n"
    "        text = VL_RERANKER_PROC.apply_chat_template(\n"
    "            messages, tokenize=False, add_generation_prompt=True\n"
    "        )\n"
    "        texts_for_proc.append(text)\n"
    "        all_messages.append(messages)\n"
    "\n"
    "    image_inputs = []\n"
    "    for msg in all_messages:\n"
    "        img_inp, _ = process_vision_info(msg)\n"
    "        if img_inp:\n"
    "            image_inputs.extend(img_inp)\n"
    "\n"
    "    inputs = VL_RERANKER_PROC(\n"
    "        text=texts_for_proc,\n"
    "        images=image_inputs if image_inputs else None,\n"
    "        return_tensors='pt',\n"
    "        padding=True,\n"
    "        truncation=True,\n"
    "        max_length=1024,\n"
    "    ).to('cuda')\n"
    "\n"
    "    out = VL_RERANKER_MODEL(**inputs)\n"
    "    last_logits = out.logits[:, -1, :]  # (batch, vocab)\n"
    "\n"
    "    scores = []\n"
    "    for i in range(len(frag_texts)):\n"
    "        y = last_logits[i, _YES_ID].item() if _YES_ID >= 0 else 0.0\n"
    "        n = last_logits[i, _NO_ID].item()  if _NO_ID  >= 0 else 0.0\n"
    "        scores.append(float(torch.softmax(torch.tensor([y, n]), dim=0)[0]))\n"
    "    return scores\n"
    "\n"
    "\n"
    "def _build_frag_text(row):\n"
    "    parts = []\n"
    "    for col in ('name', 'brand', 'top_notes', 'middle_notes', 'base_notes',\n"
    "                'main_accords', 'vibe_sentence', 'likely_occasion'):\n"
    "        v = str(row.get(col, '') or '')\n"
    "        if v and v.lower() not in ('nan', 'none', ''):\n"
    "            parts.append(v)\n"
    "    return ' | '.join(parts)[:400]\n"
    "\n"
    "\n"
    "def _context_str(ctx):\n"
    "    parts = [p for p in [ctx.eventType, ctx.timeOfDay, ctx.mood,\n"
    "                         getattr(ctx, 'customNotes', None)] if p]\n"
    "    return ', '.join(parts) if parts else 'general occasion'\n"
    "\n"
    "\n"
    "class VibeScentEngine:\n"
    "    \"\"\"Qwen3-VL unified stack: embed -> cosine retrieve -> VL batch-rerank.\"\"\"\n"
    "\n"
    "    def __init__(self, *, fragrance_df, corpus_embeddings, locked_cache=None):\n"
    "        self._df     = fragrance_df.reset_index(drop=True)\n"
    "        self._corpus = corpus_embeddings  # already L2-normed\n"
    "        self._cache  = locked_cache or {}\n"
    "\n"
    "    def recommend(self, *, request, image_bytes):\n"
    "        t0 = time.perf_counter()\n"
    "        ctx = request.context\n"
    "        cache_key = f'{ctx.eventType}|{ctx.timeOfDay}|{ctx.mood}'\n"
    "        if cache_key in self._cache:\n"
    "            return RecommendResponse(\n"
    "                recommendations=[\n"
    "                    FragranceRecommendation(**r)\n"
    "                    for r in self._cache[cache_key]['recommendations']\n"
    "                ]\n"
    "            )\n"
    "\n"
    "        ctx_str = _context_str(ctx)\n"
    "\n"
    "        # ── Retrieval ─────────────────────────────────────────────────────\n"
    "        q_vec = _embed_query(ctx_str, image_bytes)       # (1, D)\n"
    "        scores = (self._corpus @ q_vec.T).squeeze(1)    # (N,)\n"
    "\n"
    "        struct_scores = compute_structured_scores(ctx, self._df)\n"
    "        _lo, _hi = struct_scores.min(), struct_scores.max()\n"
    "        struct_norm = (struct_scores - _lo) / max(_hi - _lo, 1e-9)\n"
    "        fused = 0.85 * scores + 0.15 * struct_norm\n"
    "\n"
    "        top_idx = np.argpartition(-fused, _TOPK)[:_TOPK]\n"
    "        top_idx = top_idx[np.argsort(-fused[top_idx])]\n"
    "\n"
    "        print(f'  Retrieval done ({time.perf_counter()-t0:.1f}s). '\n"
    "              f'Top: {self._df.iloc[top_idx[0]].get(\"name\", \"?\")}')\n"
    "\n"
    "        # ── Batch rerank: one forward pass for all _TOPK candidates ──────\n"
    "        frag_texts = [_build_frag_text(self._df.iloc[int(i)]) for i in top_idx]\n"
    "        try:\n"
    "            rerank_scores = _rerank_batch(ctx_str, frag_texts, image_bytes)\n"
    "        except Exception as _e:\n"
    "            print(f'  Batch reranker failed: {_e} — falling back to fusion scores')\n"
    "            rerank_scores = [float(fused[int(i)]) for i in top_idx]\n"
    "\n"
    "        _ranked = sorted(zip(top_idx, rerank_scores),\n"
    "                         key=lambda x: x[1], reverse=True)\n"
    "        final_top = _ranked[:_FINAL]\n"
    "\n"
    "        print(f'  Reranking done ({time.perf_counter()-t0:.1f}s). '\n"
    "              f'Final top: {self._df.iloc[final_top[0][0]].get(\"name\", \"?\")}')\n"
    "\n"
    "        # ── Build response ────────────────────────────────────────────────\n"
    "        recs = []\n"
    "        for rank, (idx, rr_score) in enumerate(final_top, start=1):\n"
    "            row   = self._df.iloc[int(idx)]\n"
    "            name  = str(row.get('name',  f'Fragrance #{idx}'))\n"
    "            house = str(row.get('brand', 'Unknown'))\n"
    "            notes = []\n"
    "            for col in ('top_notes', 'middle_notes', 'base_notes', 'main_accords'):\n"
    "                v = str(row.get(col, '') or '')\n"
    "                if v and v.lower() not in ('nan', 'none', ''):\n"
    "                    notes += [n.strip() for n in v.split(',') if n.strip()]\n"
    "            notes = list(dict.fromkeys(notes))[:8]\n"
    "            vibe = str(row.get('vibe_sentence', '') or '')\n"
    "            if vibe.lower() in ('nan', 'none', ''): vibe = ''\n"
    "            reasoning = vibe or f'Matched for {ctx_str} (score: {rr_score:.3f})'\n"
    "            occ_lbl = str(row.get('likely_occasion', ctx_str) or ctx_str)\n"
    "            if occ_lbl.lower() in ('nan', 'none', ''): occ_lbl = ctx_str\n"
    "            recs.append(FragranceRecommendation(\n"
    "                rank=rank, name=name, house=house,\n"
    "                score=round(rr_score, 4),\n"
    "                notes=notes, reasoning=reasoning, occasion=occ_lbl,\n"
    "            ))\n"
    "\n"
    "        print(f'  Total latency: {time.perf_counter()-t0:.1f}s')\n"
    "        return RecommendResponse(recommendations=recs)\n"
    "\n"
    "\n"
    "ENGINE = VibeScentEngine(\n"
    "    fragrance_df=FRAGRANCE_DF,\n"
    "    corpus_embeddings=CORPUS_EMBEDDINGS,\n"
    ")\n"
    "print(f'VibeScentEngine (w5v1) built. corpus={len(FRAGRANCE_DF)} fragrances  '\n"
    "      f'[batch reranker, _TOPK={_TOPK}]')\n"
)

nb['cells'][4]['source'] = [stage3_new]
nb['cells'][5]['source'] = [stage4_new]

with open(NB_PATH, 'w') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("Written.")

# Verify
with open(NB_PATH) as f:
    nb2 = json.load(f)
c4 = ''.join(nb2['cells'][4]['source'])
c5 = ''.join(nb2['cells'][5]['source'])
print(f"Cell4 TF32:            {'allow_tf32' in c4}")
print(f"Cell4 flash_attention: {'flash_attention_2' in c4}")
print(f"Cell4 torch.compile:   {'torch.compile' in c4}")
print(f"Cell5 _TOPK=8:         {'_TOPK  = 8' in c5}")
print(f"Cell5 _rerank_batch:   {'_rerank_batch' in c5}")
print(f"Cell5 batch fallback:  {'Batch reranker failed' in c5}")
